name: CHAT ACTION

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: readCode
        uses: actions/checkout@v4

      - name: setUp_node_v24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: install_ci_dependency
        run: npm ci

      - name: type_check
        run: npx tsc --noEmit

      - name: check_docker_build
        run: docker build -t chatapp .

      - name: validate_docker_compose
        run: docker compose config